# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: harbor
    component: exporter
  name: exporter
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: harbor
      component: exporter
  template:
    metadata:
      labels:
        app: harbor
        component: exporter
    spec:
      securityContext:
        fsGroup: 10000
        runAsUser: 10000
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      containers:
      - name: exporter
        image: goharbor/harbor-exporter
        imagePullPolicy: IfNotPresent
        args:
          - -log-level
          - info
        livenessProbe:
          httpGet:
            path: /
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8001
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
        envFrom:
        - configMapRef:
            name: exporter
        - secretRef:
            name: exporter      
        ports:
        - containerPort: 8080
      volumes:
      - name: config
        secret:
          secretName: exporter